/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\幻想乡\\Desktop\\Github\\vuepress\\yjkblog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-59bb6e94",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-59bb6e94").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-4ddec33a",
    path: "/blogs/category2/2016/121501.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4ddec33a").then(next)
    },
  },
  {
    name: "v-2b49becd",
    path: "/blogs/other/guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2b49becd").then(next)
    },
  },
  {
    name: "v-9ff679cc",
    path: "/blogs/category1/2019/092101.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9ff679cc").then(next)
    },
  },
  {
    name: "v-26bbb24c",
    path: "/blogs/category1/2018/121501.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-26bbb24c").then(next)
    },
  },
  {
    name: "v-11415f7a",
    path: "/blogs/category2/2017/092101.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-11415f7a").then(next)
    },
  },
  {
    name: "v-0fc76610",
    path: "/pages/f344d070a1031ef7/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0fc76610").then(next)
    },
  },
  {
    path: "/pages/f344d070a1031ef7/index.html",
    redirect: "/pages/f344d070a1031ef7/"
  },
  {
    path: "/blogs/前端标准化/ESLint.html",
    redirect: "/pages/f344d070a1031ef7/"
  },
  {
    name: "v-7a8e90ce",
    path: "/pages/c1edd70a6b7c7872/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7a8e90ce").then(next)
    },
  },
  {
    path: "/pages/c1edd70a6b7c7872/index.html",
    redirect: "/pages/c1edd70a6b7c7872/"
  },
  {
    path: "/blogs/《ES6 教程》笔记/02.let 和 const 命令.html",
    redirect: "/pages/c1edd70a6b7c7872/"
  },
  {
    name: "v-2b6b1e91",
    path: "/pages/b1ab10a62f7564da/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2b6b1e91").then(next)
    },
  },
  {
    path: "/pages/b1ab10a62f7564da/index.html",
    redirect: "/pages/b1ab10a62f7564da/"
  },
  {
    path: "/blogs/《ES6 教程》笔记/03.变量的解构赋值.html",
    redirect: "/pages/b1ab10a62f7564da/"
  },
  {
    name: "v-14de622d",
    path: "/pages/ca89eca8adeba5f4/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-14de622d").then(next)
    },
  },
  {
    path: "/pages/ca89eca8adeba5f4/index.html",
    redirect: "/pages/ca89eca8adeba5f4/"
  },
  {
    path: "/blogs/《ES6 教程》笔记/04.字符串的扩展.html",
    redirect: "/pages/ca89eca8adeba5f4/"
  },
  {
    name: "v-c085bf28",
    path: "/pages/a650b4a0ebfc9350/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c085bf28").then(next)
    },
  },
  {
    path: "/pages/a650b4a0ebfc9350/index.html",
    redirect: "/pages/a650b4a0ebfc9350/"
  },
  {
    path: "/blogs/《ES6 教程》笔记/05.字符串的新增方法.html",
    redirect: "/pages/a650b4a0ebfc9350/"
  },
  {
    name: "v-9a69caf4",
    path: "/pages/0473261a6ab0ee8c/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9a69caf4").then(next)
    },
  },
  {
    path: "/pages/0473261a6ab0ee8c/index.html",
    redirect: "/pages/0473261a6ab0ee8c/"
  },
  {
    path: "/blogs/《ES6 教程》笔记/06.正则的扩展.html",
    redirect: "/pages/0473261a6ab0ee8c/"
  },
  {
    name: "v-fc1b12ae",
    path: "/pages/8ed309d668b20264/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fc1b12ae").then(next)
    },
  },
  {
    path: "/pages/8ed309d668b20264/index.html",
    redirect: "/pages/8ed309d668b20264/"
  },
  {
    path: "/blogs/《ES6 教程》笔记/08.函数的扩展.html",
    redirect: "/pages/8ed309d668b20264/"
  },
  {
    name: "v-7a34a994",
    path: "/pages/5dfea9a0f2d1a392/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7a34a994").then(next)
    },
  },
  {
    path: "/pages/5dfea9a0f2d1a392/index.html",
    redirect: "/pages/5dfea9a0f2d1a392/"
  },
  {
    path: "/blogs/《ES6 教程》笔记/07.数值的扩展.html",
    redirect: "/pages/5dfea9a0f2d1a392/"
  },
  {
    name: "v-5ff2d8b6",
    path: "/pages/b5e3e0a0ff6e9c25/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5ff2d8b6").then(next)
    },
  },
  {
    path: "/pages/b5e3e0a0ff6e9c25/index.html",
    redirect: "/pages/b5e3e0a0ff6e9c25/"
  },
  {
    path: "/blogs/《ES6 教程》笔记/10.对象的扩展.html",
    redirect: "/pages/b5e3e0a0ff6e9c25/"
  },
  {
    name: "v-5d8cba3a",
    path: "/pages/e34009d60d8bc4b2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5d8cba3a").then(next)
    },
  },
  {
    path: "/pages/e34009d60d8bc4b2/index.html",
    redirect: "/pages/e34009d60d8bc4b2/"
  },
  {
    path: "/blogs/《ES6 教程》笔记/09.数组的扩展.html",
    redirect: "/pages/e34009d60d8bc4b2/"
  },
  {
    name: "v-2534c2cf",
    path: "/pages/e85e68947502cf90/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2534c2cf").then(next)
    },
  },
  {
    path: "/pages/e85e68947502cf90/index.html",
    redirect: "/pages/e85e68947502cf90/"
  },
  {
    path: "/blogs/《ES6 教程》笔记/11.对象的新增方法.html",
    redirect: "/pages/e85e68947502cf90/"
  },
  {
    name: "v-b76c5fe0",
    path: "/pages/02c86eb2792f3262/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b76c5fe0").then(next)
    },
  },
  {
    path: "/pages/02c86eb2792f3262/index.html",
    redirect: "/pages/02c86eb2792f3262/"
  },
  {
    path: "/blogs/《ES6 教程》笔记/12.Symbol.html",
    redirect: "/pages/02c86eb2792f3262/"
  },
  {
    name: "v-2b5169de",
    path: "/pages/0c21dae358fca16b/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2b5169de").then(next)
    },
  },
  {
    path: "/pages/0c21dae358fca16b/index.html",
    redirect: "/pages/0c21dae358fca16b/"
  },
  {
    path: "/blogs/《ES6 教程》笔记/13.Set 和 Map 数据结构.html",
    redirect: "/pages/0c21dae358fca16b/"
  },
  {
    name: "v-e63e0d48",
    path: "/pages/74de3e45e4491e95/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e63e0d48").then(next)
    },
  },
  {
    path: "/pages/74de3e45e4491e95/index.html",
    redirect: "/pages/74de3e45e4491e95/"
  },
  {
    path: "/blogs/《ES6 教程》笔记/15.Reflect.html",
    redirect: "/pages/74de3e45e4491e95/"
  },
  {
    name: "v-13d78db2",
    path: "/pages/48df907ad3570f3d/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-13d78db2").then(next)
    },
  },
  {
    path: "/pages/48df907ad3570f3d/index.html",
    redirect: "/pages/48df907ad3570f3d/"
  },
  {
    path: "/blogs/《ES6 教程》笔记/17.Iterator 和 for-of 循环.html",
    redirect: "/pages/48df907ad3570f3d/"
  },
  {
    name: "v-6a432548",
    path: "/pages/f56ec2ab97d60483/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6a432548").then(next)
    },
  },
  {
    path: "/pages/f56ec2ab97d60483/index.html",
    redirect: "/pages/f56ec2ab97d60483/"
  },
  {
    path: "/blogs/《ES6 教程》笔记/14.Proxy.html",
    redirect: "/pages/f56ec2ab97d60483/"
  },
  {
    name: "v-438860be",
    path: "/pages/2810ae8985e9bd52/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-438860be").then(next)
    },
  },
  {
    path: "/pages/2810ae8985e9bd52/index.html",
    redirect: "/pages/2810ae8985e9bd52/"
  },
  {
    path: "/blogs/《ES6 教程》笔记/16.Promise 对象.html",
    redirect: "/pages/2810ae8985e9bd52/"
  },
  {
    name: "v-6cc3cc1e",
    path: "/pages/75af7031eb66847b/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6cc3cc1e").then(next)
    },
  },
  {
    path: "/pages/75af7031eb66847b/index.html",
    redirect: "/pages/75af7031eb66847b/"
  },
  {
    path: "/blogs/《ES6 教程》笔记/19.Generator 函数的异步应用.html",
    redirect: "/pages/75af7031eb66847b/"
  },
  {
    name: "v-01d7a7b2",
    path: "/pages/718b48ed9ce0adce/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-01d7a7b2").then(next)
    },
  },
  {
    path: "/pages/718b48ed9ce0adce/index.html",
    redirect: "/pages/718b48ed9ce0adce/"
  },
  {
    path: "/blogs/《ES6 教程》笔记/18.Generator 函数的语法.html",
    redirect: "/pages/718b48ed9ce0adce/"
  },
  {
    name: "v-12a8e728",
    path: "/pages/3777253e65bac487/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-12a8e728").then(next)
    },
  },
  {
    path: "/pages/3777253e65bac487/index.html",
    redirect: "/pages/3777253e65bac487/"
  },
  {
    path: "/blogs/《ES6 教程》笔记/20.async 函数.html",
    redirect: "/pages/3777253e65bac487/"
  },
  {
    name: "v-47b76100",
    path: "/pages/e831e1593c82bbe0/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-47b76100").then(next)
    },
  },
  {
    path: "/pages/e831e1593c82bbe0/index.html",
    redirect: "/pages/e831e1593c82bbe0/"
  },
  {
    path: "/blogs/《ES6 教程》笔记/21.Class 的基本语法.html",
    redirect: "/pages/e831e1593c82bbe0/"
  },
  {
    name: "v-39f253f8",
    path: "/pages/83f8c3a0cd87dd83/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-39f253f8").then(next)
    },
  },
  {
    path: "/pages/83f8c3a0cd87dd83/index.html",
    redirect: "/pages/83f8c3a0cd87dd83/"
  },
  {
    path: "/blogs/《ES6 教程》笔记/22.Class 的继承.html",
    redirect: "/pages/83f8c3a0cd87dd83/"
  },
  {
    name: "v-737f22ee",
    path: "/pages/efe2fb04eb8ac5fb/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-737f22ee").then(next)
    },
  },
  {
    path: "/pages/efe2fb04eb8ac5fb/index.html",
    redirect: "/pages/efe2fb04eb8ac5fb/"
  },
  {
    path: "/blogs/《ES6 教程》笔记/23.Module 的语法.html",
    redirect: "/pages/efe2fb04eb8ac5fb/"
  },
  {
    name: "v-1e548237",
    path: "/pages/a79ca2e64ceae213/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1e548237").then(next)
    },
  },
  {
    path: "/pages/a79ca2e64ceae213/index.html",
    redirect: "/pages/a79ca2e64ceae213/"
  },
  {
    path: "/blogs/《ES6 教程》笔记/24.Module 的加载实现.html",
    redirect: "/pages/a79ca2e64ceae213/"
  },
  {
    name: "v-c983e98e",
    path: "/pages/32c35f7651d6e58e/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c983e98e").then(next)
    },
  },
  {
    path: "/pages/32c35f7651d6e58e/index.html",
    redirect: "/pages/32c35f7651d6e58e/"
  },
  {
    path: "/blogs/《ES6 教程》笔记/26.读懂 ECMAScript 规格.html",
    redirect: "/pages/32c35f7651d6e58e/"
  },
  {
    name: "v-4c0b0454",
    path: "/pages/984bf549204bb266/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4c0b0454").then(next)
    },
  },
  {
    path: "/pages/984bf549204bb266/index.html",
    redirect: "/pages/984bf549204bb266/"
  },
  {
    path: "/blogs/《ES6 教程》笔记/25.编程风格.html",
    redirect: "/pages/984bf549204bb266/"
  },
  {
    name: "v-31c24c4f",
    path: "/pages/16121351be68691b/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-31c24c4f").then(next)
    },
  },
  {
    path: "/pages/16121351be68691b/index.html",
    redirect: "/pages/16121351be68691b/"
  },
  {
    path: "/blogs/《ES6 教程》笔记/27.异步遍历器.html",
    redirect: "/pages/16121351be68691b/"
  },
  {
    name: "v-49abbeba",
    path: "/pages/7188882b8d65af1b/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-49abbeba").then(next)
    },
  },
  {
    path: "/pages/7188882b8d65af1b/index.html",
    redirect: "/pages/7188882b8d65af1b/"
  },
  {
    path: "/blogs/《ES6 教程》笔记/29.最新提案.html",
    redirect: "/pages/7188882b8d65af1b/"
  },
  {
    name: "v-2f750624",
    path: "/pages/1cf50330655efc69/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2f750624").then(next)
    },
  },
  {
    path: "/pages/1cf50330655efc69/index.html",
    redirect: "/pages/1cf50330655efc69/"
  },
  {
    path: "/blogs/《ES6 教程》笔记/31.函数式编程.html",
    redirect: "/pages/1cf50330655efc69/"
  },
  {
    name: "v-28b5b13c",
    path: "/pages/6a8e2dc558da1b39/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-28b5b13c").then(next)
    },
  },
  {
    path: "/pages/6a8e2dc558da1b39/index.html",
    redirect: "/pages/6a8e2dc558da1b39/"
  },
  {
    path: "/blogs/《ES6 教程》笔记/32.Mixin.html",
    redirect: "/pages/6a8e2dc558da1b39/"
  },
  {
    name: "v-62ed22c8",
    path: "/pages/a2ba314746bfdbdd/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-62ed22c8").then(next)
    },
  },
  {
    path: "/pages/a2ba314746bfdbdd/index.html",
    redirect: "/pages/a2ba314746bfdbdd/"
  },
  {
    path: "/blogs/《ES6 教程》笔记/28.ArrayBuffer.html",
    redirect: "/pages/a2ba314746bfdbdd/"
  },
  {
    name: "v-28794364",
    path: "/pages/8e8f80f69b775a56/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-28794364").then(next)
    },
  },
  {
    path: "/pages/8e8f80f69b775a56/index.html",
    redirect: "/pages/8e8f80f69b775a56/"
  },
  {
    path: "/blogs/《ES6 教程》笔记/33.SIMD.html",
    redirect: "/pages/8e8f80f69b775a56/"
  },
  {
    name: "v-3c35f69d",
    path: "/pages/e97bc1e5626b082c/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3c35f69d").then(next)
    },
  },
  {
    path: "/pages/e97bc1e5626b082c/index.html",
    redirect: "/pages/e97bc1e5626b082c/"
  },
  {
    path: "/blogs/《ES6 教程》笔记/30.装饰器.html",
    redirect: "/pages/e97bc1e5626b082c/"
  },
  {
    name: "v-6f26cac3",
    path: "/pages/ea6f3b870f6dab69/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6f26cac3").then(next)
    },
  },
  {
    path: "/pages/ea6f3b870f6dab69/index.html",
    redirect: "/pages/ea6f3b870f6dab69/"
  },
  {
    path: "/blogs/《ES6 教程》笔记/34.参考链接.html",
    redirect: "/pages/ea6f3b870f6dab69/"
  },
  {
    name: "v-02772db8",
    path: "/docs/theme-reco/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-02772db8").then(next)
    },
  },
  {
    path: "/docs/theme-reco/index.html",
    redirect: "/docs/theme-reco/"
  },
  {
    name: "v-5898f432",
    path: "/docs/theme-reco/api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5898f432").then(next)
    },
  },
  {
    name: "v-4d610086",
    path: "/docs/theme-reco/plugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4d610086").then(next)
    },
  },
  {
    name: "v-18cf0bf2",
    path: "/docs/theme-reco/theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-18cf0bf2").then(next)
    },
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-1368f1e8",
    path: "/tag/tag3/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-1368f1e8").then(next)
    },
    meta: {"pid":"tags","id":"tag3"}
  },
  {
    path: "/tag/tag3/index.html",
    redirect: "/tag/tag3/"
  },
  {
    name: "v-1368f226",
    path: "/tag/tag2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-1368f226").then(next)
    },
    meta: {"pid":"tags","id":"tag2"}
  },
  {
    path: "/tag/tag2/index.html",
    redirect: "/tag/tag2/"
  },
  {
    name: "v-1368f264",
    path: "/tag/tag1/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-1368f264").then(next)
    },
    meta: {"pid":"tags","id":"tag1"}
  },
  {
    path: "/tag/tag1/index.html",
    redirect: "/tag/tag1/"
  },
  {
    name: "v-1368f1aa",
    path: "/tag/tag4/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-1368f1aa").then(next)
    },
    meta: {"pid":"tags","id":"tag4"}
  },
  {
    path: "/tag/tag4/index.html",
    redirect: "/tag/tag4/"
  },
  {
    name: "v-7c0b72d8",
    path: "/tag/ESLint/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-7c0b72d8").then(next)
    },
    meta: {"pid":"tags","id":"ESLint"}
  },
  {
    path: "/tag/ESLint/index.html",
    redirect: "/tag/ESLint/"
  },
  {
    name: "v-3257dcde",
    path: "/tag/ES6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-3257dcde").then(next)
    },
    meta: {"pid":"tags","id":"ES6"}
  },
  {
    path: "/tag/ES6/index.html",
    redirect: "/tag/ES6/"
  },
  {
    name: "v-5ce69b59",
    path: "/categories/category2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-5ce69b59").then(next)
    },
    meta: {"pid":"categories","id":"category2"}
  },
  {
    path: "/categories/category2/index.html",
    redirect: "/categories/category2/"
  },
  {
    name: "v-5ce69b3a",
    path: "/categories/category1/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-5ce69b3a").then(next)
    },
    meta: {"pid":"categories","id":"category1"}
  },
  {
    path: "/categories/category1/index.html",
    redirect: "/categories/category1/"
  },
  {
    name: "v-f6343622",
    path: "/categories/前端标准化/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-f6343622").then(next)
    },
    meta: {"pid":"categories","id":"前端标准化"}
  },
  {
    path: "/categories/前端标准化/index.html",
    redirect: "/categories/前端标准化/"
  },
  {
    name: "v-b2aef3ee",
    path: "/categories/《ES6 教程》笔记/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-b2aef3ee").then(next)
    },
    meta: {"pid":"categories","id":"《ES6 教程》笔记"}
  },
  {
    path: "/categories/《ES6 教程》笔记/index.html",
    redirect: "/categories/《ES6 教程》笔记/"
  },
  {
    name: "v-1d4b4f0c",
    path: "/tag/ES6/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1d4b4f0c").then(next)
    },
    meta: {"pid":"tags","id":"ES6"}
  },
  {
    path: "/tag/ES6/page/2/index.html",
    redirect: "/tag/ES6/page/2/"
  },
  {
    name: "v-1d4b4f2b",
    path: "/tag/ES6/page/3/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1d4b4f2b").then(next)
    },
    meta: {"pid":"tags","id":"ES6"}
  },
  {
    path: "/tag/ES6/page/3/index.html",
    redirect: "/tag/ES6/page/3/"
  },
  {
    name: "v-1d4b4f4a",
    path: "/tag/ES6/page/4/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1d4b4f4a").then(next)
    },
    meta: {"pid":"tags","id":"ES6"}
  },
  {
    path: "/tag/ES6/page/4/index.html",
    redirect: "/tag/ES6/page/4/"
  },
  {
    name: "v-60d96394",
    path: "/categories/《ES6 教程》笔记/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-60d96394").then(next)
    },
    meta: {"pid":"categories","id":"《ES6 教程》笔记"}
  },
  {
    path: "/categories/《ES6 教程》笔记/page/2/index.html",
    redirect: "/categories/《ES6 教程》笔记/page/2/"
  },
  {
    name: "v-60d963b3",
    path: "/categories/《ES6 教程》笔记/page/3/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-60d963b3").then(next)
    },
    meta: {"pid":"categories","id":"《ES6 教程》笔记"}
  },
  {
    path: "/categories/《ES6 教程》笔记/page/3/index.html",
    redirect: "/categories/《ES6 教程》笔记/page/3/"
  },
  {
    name: "v-60d963d2",
    path: "/categories/《ES6 教程》笔记/page/4/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-60d963d2").then(next)
    },
    meta: {"pid":"categories","id":"《ES6 教程》笔记"}
  },
  {
    path: "/categories/《ES6 教程》笔记/page/4/index.html",
    redirect: "/categories/《ES6 教程》笔记/page/4/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]